---
downloads: ~/.ansible-downloads/

configure_osx: false

# Set to 'true' to configure the Dock via dockutil.
configure_dock: true
dockitems_remove:
 - TV
 - Podcasts
 - News
 - Mail
 - Contacts
 - Calendar
 - Reminders
 - Maps
 - Photos
 - FaceTime
 - Notes
 - Music
 - 'System Settings'
 - Safari
 - Freeform
dockitems_persist:
 - name: 'Steam'
   path: '/Applications/Steam.app'
   pos: 4
 - name: 'Google Chrome'
   path: '/Applications/Google Chrome.app'
   pos: 5
 - name: 'Airmail Business'
   path: '/Applications/Airmail Business.app'
   pos: 6
 - name: 'Fantastical'
   path: '/Applications/Fantastical.app'
   pos: 7   
 - name: 'Discord'
   path: '/Applications/Discord.app'
   pos: 8
 - name: 'Visual Studio Code'
   path: '/Applications/Visual Studio Code.app'
   pos: 9
 - name: 'iTerm'
   path: '/Applications/iTerm.app'
   pos: 10

configure_sudoers: false
sudoers_custom_config: ''
# Example:
# sudoers_custom_config: |
#   # Allow users in admin group to use sudo with no password.
#   %admin ALL=(ALL) NOPASSWD: ALL

homebrew_installed_packages:
  - git
  - gh
  - go
  - gpg
  - openssl
  - cmake
  - sdl2
  - sdl2_image
  - sdl2_ttf
  - sdl2_mixer
  - sdl2_net
  - openal-soft

homebrew_taps: []

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - google-chrome
  - visual-studio-code
  - discord
  - doxygen
  - iterm2
  - steam
  - microsoft-remote-desktop
  - beyond-compare

# See `geerlingguy.mas` role documentation for usage instructions.
mas_installed_apps:
  - { id: 1352778147, name: "Bitwarden" }
  - { id: 1451685025, name: "Wireguard" }
  - { id: 497799835,  name: "Xcode" }
  - { id: 1538878817, name: "UTM" }
  - { id: 1530968324, name: "Airmail for Business" }
  - { id: 975937182,  name: "Fantastical" }
mas_email: "raynorpat@gmail.com"
mas_password: ""
mas_signin_dialog: true

osx_script: "~/.osx --no-restart"

# Glob pattern to ansible task files to run after all other tasks are finished.
post_provision_tasks: []