- name: Configure host.
  hosts: all

  vars_files:
    - default.config.yml

  vars:
    basic_dirs:
      - { path: "{{ lookup('env', 'HOME') }}/Projects",
          state: directory }

  pre_tasks:
    - name: Include playbook configuration.
      include_vars: "{{ item }}"
      with_fileglob:
        - "{{ playbook_dir }}/config.yml"
      tags: ['always']    

  roles:
    - role: elliotweiser.osx-command-line-tools
    - role: geerlingguy.mac.homebrew
      tags: ['homebrew']
    - role: geerlingguy.mac.mas
      tags: ['mas']
    - role: geerlingguy.mac.dock
      tags: ['dock']

  tasks:
    - import_tasks: tasks/sudoers.yml
      when: configure_sudoers
      tags: ['sudoers']

    - name: Create basic directories under home directory.
      file:
        path: "{{ item.path }}"
        state: "{{ item.state }}"
      with_items: "{{ basic_dirs }}"

    - import_tasks: tasks/osx.yml
      when: configure_osx
      tags: ['osx']        

    - name: Run post-provision task files in a block.
      tags: ['post']
      block:
        - name: Run configured post-provision ansible task files.
          include_tasks: "{{ outer_item }}"
          loop_control:
            loop_var: outer_item
          with_fileglob: "{{ post_provision_tasks | default(omit) }}"
